events {}            # bloc obligatoire, même vide. Il configure la gestion des connexions

http {       # c'est l'emboitement exigé par le format. Je ne le choisis pas
    server {
        listen 80;   # Nginx écoute sur le port 80

        location / {    # pour toutes les adresses
            proxy_pass http://api:3000;     # transmettre au service api port 3000
        }
    }
}